* se reordenan variables * se corrigen errores * se completan algunas funciones

diff --git a/variables b/variables
--- a/variables
+++ b/variables
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# Made by Sinfallas <sinfallas@yahoo.com>
+# Licence: GPL-2
 LC_ALL=C
 memoria=$(grep "MemTotal" /proc/meminfo | awk '{print $2}')
 cpu=$(lscpu | grep "MHz" | awk '{print $3}')
@@ -7,10 +9,11 @@ quien=$(who | cut -d' ' -f1 | sort | uniq)
 update="apt -q update"
 insta="apt -q -y install"
 miyad='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6'
-errores='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="ERROR"'
-advertencia='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --title="ADVERTENCIA"'
-final='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="FINALIZADO"'
+errores='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --window-icon=error --text-align=fill --borders=6 --timeout=3 --title="Error"'
+advertencia='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --title="Advertencia"'
+final='yad --skip-taskbar --button=ACEPTAR:0 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="Finalizado"'
 progreso='yad --fixed --progress --pulsate --auto-close --skip-taskbar --center'
+null="echo 1 > /dev/null"
 
 function yadinstall () {
 	if ! [[ -f /usr/bin/yad ]]; then
@@ -29,7 +32,7 @@ function rootyad () {
 
 function rootcli () {
 	if [[ "$EUID" != "0" ]]; then
-		echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+		echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
 		exit 1
 	fi
 }
@@ -74,7 +77,7 @@ function iptables_clean () {
 }
 
 function optimizacion_1 () {
-	if ! [[ -f /root/.optimizado2 ]]; then
+	if ! [[ -f /root/.optimizado ]]; then
 		if (( $memoria > 4096000 )); then
 			for i in $quien; do
 				echo "tmpfs /home/$i/.cache tmpfs noatime,noexec,nosuid,async,nodev,rw 0 0" >> /etc/fstab
@@ -82,6 +85,6 @@ function optimizacion_1 () {
 		fi
 		chage -M 183 "$quien"
 		adduser "$quien" sambashare
-		touch /root/.optimizado2
+		touch /root/.optimizado
 	fi
 }
